### ISSUE TITLE
Support plugin config

### ISSUE THREAD

**Issue by musaprg** [otelwasm/otelwasm#8]
This feature allows users to pass plugin-specific configuration to control the behavior of wasm plugins.

```yaml
processors:
  wasm:
    config:
      send_batch_size: 10000
      timeout: 10
```
