### ISSUE TITLE
Support wasm runtime config

### ISSUE THREAD

**Issue by musaprg** [otelwasm/otelwasm#9]
related: https://github.com/musaprg/otelwasm/issues/5

```
processor:
  wasm:
    runtime:
      # Allow wasm-runtime-specific configuration here
```
